# Site settings
title: DIST
description: "Web制作にまつわるあらゆることを、 みんなで集まって学んでいく新しい会"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dist.tokyo" # the base hostname & protocol for your site
twitter_username: dist_jp
github_username: distjp

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [tables, autolink, strikethrough]

# Filtering Content
future: true

# Collections
collections:
  number_series:
    output: true
    permalink: /number-series/:path/
  staff:
    output: false